In [3]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
a = [1,2, 3, "hello"]
a

[1, 2, 3, 'hello']

In [6]:
np.array(a)

array(['1', '2', '3', 'hello'], dtype='<U21')

In [8]:
l = [[1,2,3], [4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr = np.arange(1,11, 2)
arr


array([1, 3, 5, 7, 9])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [15]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [23]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [22]:
arr = np.linspace(1,5,6)
arr

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [24]:
np.random.rand(10)

array([0.64551892, 0.57811545, 0.10391241, 0.52997094, 0.5227307 ,
       0.85825302, 0.37405729, 0.89597971, 0.34347363, 0.96201741])

In [4]:
np.random.randn(10)

array([ 0.2223591 , -0.27745119, -0.63420686, -1.20706014, -0.45412945,
       -1.93072531,  0.00548716,  0.89849775, -0.02105591,  0.72719511])

In [5]:
np.random.randint(6)

1

In [6]:
np.random.randint(10,20,10)

array([15, 13, 11, 12, 12, 19, 19, 17, 19, 15], dtype=int32)

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr.shape

(3, 3)

In [10]:
arr.size

9

In [11]:
arr.dtype

dtype('int64')

# Array Methods

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.min()

np.int64(1)

In [14]:
arr.max()

np.int64(9)

In [15]:
arr.sum()

np.int64(45)

In [16]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [17]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [18]:
arr.mean()

np.float64(5.0)

In [19]:
arr.std()

np.float64(2.581988897471611)

In [20]:
arr.argmax()

np.int64(8)

In [21]:
arr.argmin()

np.int64(0)

In [22]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [26]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [27]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])