In [2]:
import numpy as np

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [14]:
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [15]:
np.sum(s,axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [11]:
b = np.sum(s,axis=1) #rows axis is 1
for i in b: 
    if i != 45:
        print("sudoku is not valid")
        break

In [12]:
a = np.sum(s,axis=0) #columns axis is 0
for i in a:
    if i != 45:
        print("sudoku is not valid")
        break

In [20]:
np.sum(s[0:3,0:3])

np.int64(45)

In [22]:
for i in range(0,9,3):
    for j in range(0,9,3):
        if np.sum(s[i:i+3,j:j+3]) != 45:
            print("Not a valid sudoku")
        print(np.sum(s[i:i+3,j:j+3]))

45
45
45
45
45
45
45
45
45


In [13]:
print("Valid Sudoku")

Valid Sudoku


In [71]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [72]:
data.shape

(5, 3)

In [73]:
data[0:,:1]

array([[18],
       [19],
       [17],
       [18],
       [20]])

In [74]:
    avg = data[0:,:1].mean()
    print(avg)

18.4


In [75]:
data[0:,1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [76]:
data[0:,2:].max()

np.int64(95)

In [77]:
maths = data[0:,1]
maths

array([85, 92, 76, 65, 90])

In [78]:
data[maths > 90]

array([[19, 92, 88]])

In [79]:
maths = maths + 5
maths

array([90, 97, 81, 70, 95])

In [80]:
data[data[:,0] < 19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [81]:
len(data[data[:,0] < 19])

3

In [82]:
math_avg = np.mean(data[:,1]+5)
science_avg = np.mean(data[:,2])
print(math_avg, science_avg)

86.6 83.2


In [83]:
data[(data[:,1]>= 80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [84]:
data[:,1:]

array([[85, 78],
       [92, 88],
       [76, 95],
       [65, 70],
       [90, 85]])

In [85]:
data[:,2][data[:,2] < 75] = 0

In [86]:
data 

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])